# name: Deploy FastAPI to ECS

# on:
#   workflow_run:
#     workflows: ["Build and Push Docker Image to ECR"]
#     types:
#       - completed

# env:
#   AWS_REGION: ${{ vars.AWS_REGION }}
#   AWS_ACCOUNT_ID: ${{ vars.AWS_ACCOUNT_ID }}
#   CLUSTER_NAME: ${{ vars.CLUSTER_NAME }}
#   SERVICE_NAME: ${{ vars.SERVICE_NAME }}

# jobs:
#   deploy:
#     name: Deploy to ECS
#     runs-on: ubuntu-latest

#     steps:
#       - name: Configure AWS Credentials
#         uses: aws-actions/configure-aws-credentials@v1
#         with:
#           aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
#           aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
#           aws-region: $AWS_REGION

#       - name: Deploy to ECS
#         run: |
#           aws ecs update-service \
#             --cluster $CLUSTER_NAME \
#             --service $SERVICE_NAME \
#             --force-new-deployment
