# name: Deploy Lambda Function

# on:
#   push:
#     branches:
#       - main

# jobs:
#   deploy:
#     runs-on: ubuntu-latest

#     steps:
#     - name: Checkout code
#       uses: actions/checkout@v3

#     - name: Set up Python
#       uses: actions/setup-python@v4
#       with:
#         python-version: '3.12'
    

#     - uses: actions/cache@v2
#       with:
#         path: layer/python
#         key: ${{ env.pythonLocation }}-${{ hashFiles('requirements.txt') }}

#     - name: Install dependencies
#       run: |
#         python -m venv venv
#         source venv/bin/activate
#         pip install -r requirements.txt -t layer/python

#     - name: Zip Dependencies
#       run: |
#         cd layer
#         zip -r ../layer.zip .

#     - name: Deploy Lambda Layer
#       run: |
#         aws lambda publish-layer-version \
#           --layer-name ContextualFAQDependencies \
#           --zip-file fileb://layer.zip \
#           --compatible-runtimes python3.12
#       env:
#         AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
#         AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
#         AWS_DEFAULT_REGION: us-east-1

#     - name: Zip Code
#       run: |
#         cd src
#         zip -r ../function.zip .

#     - name: Deploy Lambda Function
#       run: |
#         aws lambda update-function-code \
#           --function-name ContextualFAQBackend \
#           --zip-file fileb://function.zip

#         # Get the latest layer version and update Lambda function configuration
#         LAYER_VERSION=$(aws lambda list-layer-versions --layer-name ContextualFAQDependencies --query 'LayerVersions[0].Version' --output text)

#         aws lambda update-function-configuration \
#           --function-name ContextualFAQBackend \
#           --layers arn:aws:lambda:us-east-1:533267042349:layer:ContextualFAQDependencies:$LAYER_VERSION
#       env:
#         AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
#         AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
#         AWS_DEFAULT_REGION: us-east-1
