name: Deploy Lambda Function

on:
  push:
    branches:
      - main  # This triggers the workflow on pushes to the main branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    # Checkout the latest code
    - name: Checkout code
      uses: actions/checkout@v3

    # Set up Python environment
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'  # Ensure this matches your Lambda runtime

    # Install dependencies for packaging the layer
    - name: Install dependencies
      run: |
        python -m venv venv
        source venv/bin/activate
        pip install -r requirements.txt -t layer/python

    # Zip the Lambda function
    - name: Zip Lambda function
      run: zip -r function.zip lambda_function.py

    # Zip the Lambda layer
    - name: Zip Lambda layer
      run: |
        cd layer
        zip -r ../layer.zip .

    # Upload Lambda layer to AWS
    - name: Deploy Lambda Layer
      run: |
        aws lambda publish-layer-version \
          --layer-name ContextualFAQBackendDependencies \
          --zip-file fileb://layer.zip \
          --compatible-runtimes python3.12
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_DEFAULT_REGION: us-east-1  # Set your AWS region

    # Deploy the Lambda function with the new layer
    - name: Deploy Lambda Function
      run: |
        aws lambda update-function-code \
          --function-name ContextualFAQBackend \
          --zip-file fileb://function.zip
          
        # Get the latest layer version
        LAYER_VERSION=$(aws lambda list-layer-versions --layer-name my-lambda-layer --query 'LayerVersions[0].Version' --output text)
        
        # Update the function configuration to attach the layer
        aws lambda update-function-configuration \
          --function-name ContextualFAQBackend \
          --layers arn:aws:lambda:us-east-1:123456789012:layer:my-lambda-layer:$LAYER_VERSION
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_DEFAULT_REGION: us-east-1  # Set your AWS region
